const ACTIONS = {
    GET_PRODUCTS_REQUEST : "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS : "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAIL : "GET_PRODUCTS_FAIL",
    GET_PRODUCT_REQUEST : "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS : "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL : "GET_PRODUCT_FAIL",

}

export default ACTIONS;