const ACTIONS = {
    GET_PRODUCTS_REQUEST : "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS : "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAIL : "GET_PRODUCTS_FAIL",
    GET_PRODUCT_REQUEST : "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS : "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL : "GET_PRODUCT_FAIL",
    CART_ADD_ITEM : "CART_ADD_ITEM",
    CART_REMOVE_ITEM : "CART_REMOVE_ITEM"

}

export default ACTIONS;