const ACTIONS = {
    GET_PRODUCTS_REQUEST : "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS : "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAIL : "GET_PRODUCTS_FAIL",

    GET_PRODUCT_REQUEST : "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS : "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL : "GET_PRODUCT_FAIL",

    CART_ADD_ITEM : "CART_ADD_ITEM",
    CART_REMOVE_ITEM : "CART_REMOVE_ITEM",

    USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL : "USER_LOGIN_FAIL",
    USER_LOGOUT : "USER_LOGOUT",

    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL : "USER_REGISTER_FAIL",

    USER_DETAILS_REQUEST : "USER_DETAILS_REQUEST",
    USER_DETAILS_SUCCESS : "USER_DETAILS_SUCCESS",
    USER_DETAILS_FAIL : "USER_DETAILS_FAIL",

    USER_UPDATE_REQUEST : "USER_UPDATE_REQUEST",
    USER_UPDATE_SUCCESS : "USER_UPDATE_SUCCESS",
    USER_UPDATE_FAIL : "USER_UPDATE_FAIL",
    USER_UPDATE_RESET : "USER_UPDATE_RESET",

    CART_SAVE_SHIPPING_ADDRESS : "CART_SAVE_SHIPPING_ADDRESS",

    CART_SAVE_PAYMENT_METHOD : "CART_SAVE_PAYMENT_METHOD",


    ORDER_CREATE_REQUEST : "ORDER_CREATE_REQUEST",
    ORDER_CREATE_SUCCESS : "ORDER_CREATE_SUCCESS",
    ORDER_CREATE_FAIL : "ORDER_CREATE_FAIL",


    ORDER_DETAILS_REQUEST : "ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS : "ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAIL : "ORDER_DETAILS_FAIL",

    ORDER_PAY_REQUEST : "ORDER_PAY_REQUEST",
    ORDER_PAY_SUCCESS : "ORDER_PAY_SUCCESS",
    ORDER_PAY_FAIL : "ORDER_PAY_FAIL",
    ORDER_PAY_RESET : "ORDER_PAY_RESET",

    MY_ORDERLIST_REQUEST : "MY_ORDERLIST_REQUEST",
    MY_ORDERLIST_SUCCESS : "MY_ORDERLIST_SUCCESS",
    MY_ORDERLIST_FAIL : "MY_ORDERLIST_FAIL",

}

export default ACTIONS;